.TH DLOCATE 1 "2016-06-20" "Debian Project" "dlocate"
.\" Please adjust this date whenever revising the manpage.
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)

.SH NAME
dlocate - program to view debian package information

.SH SYNOPSIS
.B dlocate
.RI [ OPTIONS ]
.RI [ command ]
.RB [ 
.IR package .\|.\|.
|
.IR PATTERN .\|.\|.]
.

.SH "DESCRIPTION"
.PP
.B dlocate
is a fast alternative to dpkg for queries like `dpkg \-L' and `dpkg \-S'

.SH COMMANDS
.TP
.BR (none)
List all records where either the package name or the filename matches
.IR PATTERN .

Note that dlocate uses GNU grep, so normal regexp metacharacters need to be taken into account or avoided
by using the '\-F' (Fixed String) grep option.

For example, to search for `/usr/bin/[', you might try:
\fBdlocate '/usr/bin/\\['\fP
or
\fBdlocate \-F '/usr/bin/['\fP
.TP
.BR \-S
List all records where only the filename matches
.IR PATTERN .

Note that dlocate uses GNU grep, so normal regexp metacharacters need to be taken into account.
Fixed String searches are incompatible with \-S.

For example, to search for `/usr/bin/[', you need to type:

\fBdlocate  '/usr/bin/\\['\fP

.TP
.BR \-l
Regexp-enhanced emulation of `dpkg \-l'.  Shows all packages which match
.IR package .

Internally this uses grep on a file containing the reformatted
output of 'dpkg \-l' (four fields separated by tabs; status,
package-name, installed version, short description) so it will return
packages whose version or short description matches, too.

Various flavours of regular expression are supported. For example, Extended Regexp:

\fBdlocate \-l '^..[[:space:]]libc6'\fP

or Perl Regexp:

\fBdlocate \-P \-l '^..\\slibc6'\fP

Both of these will list all the packages whose names start with `libc6'.

Note that because of the difference between regular expressions and
dpkg's shell\-style pattern matching, the output from \fBdlocate \-l\fP
is occasionally different to the output from \fBdpkg \-l\fP.

This is not a bug, regular expressions are far more flexible than shell
pattern matching. This is the way dlocate is supposed to run, but it
may require some knowledge of regular expressions to get the output you
want.

.TP
.BR \-k
List package names of installed kernels and all related packages
.TP
.BR \-K
Detailed list of installed kernels and all related packages

.TP
.BR \-L
List all files in 
.IR package .

.TP
.BR \-s
Print status of
.IR package .

.TP
.BR \-\^\-ls
`ls \-ldF' of all files in
.IR package .

.TP
.BR \-\^\-lsconf
`ls \-ldF' of conffiles in
.IR package .

.TP
.BR \-\^\-conf
List conffiles in
.IR package .

.TP
.BR \-\^\-du
`du \-sck' of all files in
.IR package .

.TP
.BR \-\^\-md5sum
List md5sums (if any) of 
.IR package .

.TP
.BR \-\^\-md5check
Check md5sums (if any) of 
.IR package .

.TP
.BR \-\^\-man
List man pages (if any) in
.IR package .

.TP
.BR \-\^\-lsman
List full path/filenames of man pages (if any) in
.IR package .

.TP
.BR \-\^\-lsbin
List full path/filenames of executable files (if any) in
.IR package .

.TP
.BR \-\^\-lsdir
List only the directories in 
.IR package .

.SH OPTIONS
.TP
.BR \-\^\-filename\-only
Only output file names when searching for files

.TP
.BR \-\^\-package\-only
Only output package names when searching for files

.TP
.BR \-w ", " \-\^\-word\-regexp
Select only those lines containing matches that form whole words.
The test is that the matching substring must either be at the
beginning of the line, or preceded by a non-word constituent
character. Similarly, it must be either at the end of the line
or followed by a non-word constituent character. Word-constituent
characters are letters, digits, and the underscore.

.TP
.BR \-i ", " --ignore-case
Ignore case distinctions in the PATTERN 

.TP
.BR \-E ", " \-\^\-extended\-regexp
Interpret
.I PATTERN
as an extended regular expression.
This is the default.

.TP
.BR \-F ", " \-\^\-fixed\-strings
Interpret
.I PATTERN
as a list of fixed strings, separated by newlines,
any of which is to be matched.

.TP
.BR \-G ", " \-\^\-basic\-regexp
Interpret
.I PATTERN
as a basic regular expression.

.TP
.BR \-P ", " \-\^\-perl\-regexp
Interpret
.I PATTERN
as a Perl regular expression.
This is considered to be highly experimental within GNU grep and may warn of unimplemented features.

.TP
.BR \-h ", " \-H ", " \-\-help
Produces a short help message and exits.

.TP
.BR \-V ", " \-\-version
Display dlocate's version number and exit.

.TP
.BR \-v ", " \-\-verbose ", " \-\-debug
Produce verbose debugging output
.PP

.TP
.BR \-c ", " \-\-columns [ =\fIcolumns\fP ]
Set COLUMN width to override the \fBdlocate\fP default of using the entire terminal line width.
Any value for \fIcolumns\fP less than 80 will be increaed to 80.

.SH FILES
.TP
.I /etc/default/dlocate
Configuration file with default options. Currently the only option is
to enable/disable gzip compression of /var/lib/dlocate/dlocatedb.

.TP
.I /var/lib/dlocate/dlocatedb
Plain text listing of all files belonging to all packages (optionally compressed)

.TP
.I /var/lib/dlocate/dpkg-list
Listing of all packages known to dpkg.

See \fBupdate\-dlocatedb\fP(8) for details.

.SH EXAMPLES
To find which package `/usr/bin/[' belongs to:
.br
\fB     dlocate '/usr/bin/\\['\fP
.br

To view all man pages contained within the dpkg package:
.br
\fB     man $(dlocate \-man dpkg)\fP
.br

To purge kernel version 2.6.28.7 and all related module packages:
.br
\fB     dlocate \-k | grep \-\- \-2.6.28.7 | xargs apt\-get purge\fP
.br

To check the md5sums of the dlocate package:
.br
\fB     dlocate \-md5check dlocate\fP
.br

To use dpkg-repack to make a backup copy of all installed mythtv packages just before
upgrading them:
.br
\fB     dlocate \-l mythtv | awk '/^.i/ {print $2}' | xargs dpkg\-repack\fP
.br

.br
.nf
# dlocate \-l mythtv | awk '/^.i/ {print $2}' | xargs dpkg\-repack
.br
dpkg-deb: building package `libmythtv-perl' in `./libmythtv-perl_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv' in `./mythtv_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv-backend' in `./mythtv-backend_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv-common' in `./mythtv-common_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv-database' in `./mythtv-database_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv-doc' in `./mythtv-doc_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv-frontend' in `./mythtv-frontend_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv-perl' in `./mythtv-perl_0.21.svn20090414-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtv-status' in `./mythtv-status_0.9.0-5_amd64.deb'.
.br
dpkg-deb: building package `mythtv-themes' in `./mythtv-themes_0.21-0.0_amd64.deb'.
.br
dpkg-deb: building package `mythtvfs' in `./mythtvfs_0.5.2-2_amd64.deb'.
.br
dpkg-deb: building package `python-mythtv' in `./python-mythtv_0.21.svn20090414-0.0_amd64.deb'.
.br
.fi

.SH NOTES
\fBdlocate\fP does not update its databases (see \fBFILES\fP section)
automatically after new or upgraded packages have been installed with
\fBdpkg\fP or \fBapt-get\fP etc.
.br
.br
A daily cron job is run to perform the update.  Or the root user can
run \fPupdate-dlocatedb\fP at any time to force an update.
.br


.SH ENVIRONMENT VARIABLES
.TP
.BR COLUMNS
Sets the number of columns \fBdlocate\fP should use when displaying formatted
text. Currently only used by \-l. Values lower than 80 are increased to 80.

.SH "SEE ALSO"
\fBdpkg\fP(1),
\fBupdate\-dlocatedb\fP(8),
\fBgrep\fP(1)
and
\fBgrep\-dctrl\fP(1).

.SH AUTHOR
\fBdlocate\fP was written by Jim Pick <jim@pick.com> and Craig Sanders
<cas@taz.net.au>. dlocate is Free Software licensed under the GNU
General Public License.
