#!/bin/bash

# dpkg-hold -- command line tool to flag package(s) as held.
#
# by Craig Sanders, 1998-10-26.  This script is hereby placed into the
# public domain.
#
# 2017-09-06 update: apt-mark does this better.  My dpkg-hold etc
# scripts are now wrappers around apt-mark and continue to exist only so
# that any existing scripts that depend on them don't break..

if [ -z "$*" ]; then
  echo "Usage:"
  echo "      dpkg-hold <package...>"
  exit 1
fi

#for i in $@; do
#  echo "$i	hold"
#done | dpkg --set-selections

apt-mark hold "$@"
