=head1 NAME

dpkg-remove - mark packages for removal

=head1 SYNOPSIS

B<dpkg-remove> [I<package>...]

=head1 WARNING

This command is B<deprecated>,
and will be removed during in Debian forky,
use C<dpkg --set-selections> or C<apt-mark> instead.

=head1 DESCRIPTION

B<dpkg-remove> marks package(s) to be removed.

It achieves this by running C<dpkg --set-selections> and piping in the
package name(s) followed by B<deinstall>.

NOTE: This program does not install, remove, purge any package. It ONLY
sets the status of the package. Any actual removal or purging is done
the next time B<dselect>, B<apt-get>, B<aptitude>, etc are run.

=head1 SEE ALSO

L<dpkg(1)>,
L<apt-mark(8)>,
L<dpkg-hold(1)>,
L<dpkg-unhold(1)>,
L<dpkg-purge(1)>.
