.TH DPKG-HOLD 8 "2009-06-02" "Debian Project" "dlocate"
.\" Please adjust this date whenever revising the manpage.
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)

.SH NAME
dpkg-hold - mark packages as `hold' to prevent installation

.SH SYNOPSIS
.B dpkg-hold
.RI [ PACKAGE .\|.\|.]

.SH "DESCRIPTION"
.PP
.B dpkg-hold
marks package(s) to be held.

It achieves this by running `dpkg \-\-set\-selections' and piping in the
package name(s) followed by `hold'.

NOTE: This program does not install, remove, purge any package. It ONLY
sets the status of the package. Any actual removal or purging is done
the next time dselect, apt-get, aptitude, etc are run.

.SH "SEE ALSO"
\fBdpkg\fP(1),
\fBdpkg-unhold\fP(1),
\fBdpkg-remove\fP(1),
\fBdpkg-purge\fP(1)
