=head1 NAME

dpkg-purge - mark packages for purge

=head1 SYNOPSIS

B<dpkg-purge> [I<package>...]

=head1 DESCRIPTION

B<dpkg-purge> marks package(s) to be purged.

It achieves this by running C<dpkg --set-selections> and piping in the
package name(s) followed by B<purge>.

NOTE: This program does not install, remove, purge any package. It ONLY
sets the status of the package. Any actual removal or purging is done
the next time B<dselect>, B<apt-get>, B<aptitude>, etc are run.

=head1 SEE ALSO

L<dpkg(1)>,
L<dpkg-hold(1)>,
L<dpkg-unhold(1)>,
L<dpkg-remove(1)>.
