.TH UPDATE\-DLOCATEDB 8 "2016-06-20" "Debian Project" "dlocate"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
update\-dlocatedb - generate text database of installed files for dlocate

.SH SYNOPSIS
.B update\-dlocatedb

.SH DESCRIPTION
.B update\-dlocatedb
generates a plain text package contents listing
from the files /var/lib/dpkg/info/*.list
.PP
This program is usually called from cron.daily.

.SH OPTIONS
.TP
.BR \-p
Update the packages list only

.TP
.BR \-j
Update the files list only

.TP
.BR \-b
Update both (default)

.TP
.BR \-h
This help message


.SH FILES
.TP
.I /etc/default/dlocate
Configuration file with default options. Currently the only option is
to enable/disable gzip compression of the dlocatedb file.
.TP

.I /var/lib/dpkg/info
Directory containing dpkg file lists
.TP

.TP
.I /var/lib/dlocate/dlocatedb
Plain text listing of all files belonging to all packages (optionally compressed)

.TP
.I /var/lib/dlocate/dpkg-list
Listing of all packages known to dpkg.

This contains the reformatted output output of 'dpkg \-l'.  The file format is four fields separated by tabs:

status [TAB] package-name [TAB] installed version [TAB] short description 

The "installed version" field may contain an architecture, e.g. ":arch"


.SH SEE ALSO
.BR "dlocate(1)"
.P
.SH AUTHOR
This version of update\-dlocatedb was written by Fredrik Hallenberg,
Craig Sanders, and Pawel Chmielowski.
.PP
The manual page was written by Andreas Metzler <ametzler at
downhill.at.eu.org> for the Debian GNU/Linux system (but may be used by
others, under the terms of the GNU GPL).

