.TH DLOCATE 1 "March 2002"
.\" Please adjust this date whenever revising the manpage.
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)

.SH NAME
dlocate - program to view debian package information

.SH SYNOPSIS
.B dlocate
[ option ] [
.I package
|
.I string
]

.SH "DESCRIPTION"
.PP
.B dlocate
is a fast alternative to dpkg for queries like `dpkg -L' and `dpkg -S'

.SH OPTIONS
.TP
.B (none)
List all records where either the package name or the filename matches
.IR string .

Note that dlocate uses GNU locate for this search, so locate's caveats about
metacharacters needs to be taken into account.

For example, to search for `/usr/bin/[', you need to type:

\fBdlocate '*\\['\fP
.TP
.B \-h
Produces a short help message and exits.
.TP
.B \-h
Display dlocate's version number and exits.
.TP
.B \-S
list all records where only the filename matches
.IR string .

Note that dlocate uses GNU locate for this search, so locate's caveats about
metacharacters needs to be taken into account.

For example, to search for `/usr/bin/[', you need to type:

\fBdlocate -S '*\\['\fP

.TP
.B \-l
Simplistic emulation of `dpkg \-l'.  Shows all packages which match
.IR package .

Internally this uses egrep on a file containing the reformatted output
of `dpkg \-l' (four fields separated by one space\-character: status,
package\-name, installed version, description) so it will return
packages whose tag\-line matches, too.

Extended regular expression are allowed. For example,

\fBdlocate \-l '^.. libc5'\fP

will list all the package names starting with `libc5'.

Note that because of the difference between regular expressions and
dpkg's shell\-style pattern matching, the output from \fBdlocate -l\fP
is occasionally different to the output from \fBdpkg -l\fP.

This is not a bug, regular expressions are far more flexible than shell
pattern matching.  This is the way dlocate is supposed to run, but it
may require some knowledge of regular expressions to get the output you
want.

.TP
.B \-L
List all files in 
.IR package .
.TP
.B \-s
Print status of
.IR package .
.TP
.B \-ls
`ls \-ldF' of all files in
.IR package .
.TP
.B \-lsconf
`ls \-ldF' of conffiles in
.IR package .
.TP
.B \-conf
List conffiles in
.IR package .
.TP
.B \-du
`du \-sck' of all files in
.IR package .
.TP
.B \-md5sum
List md5sums (if any) of 
.IR package .
.TP
.B \-md5check
Check md5sums (if any) of 
.IR package .
.TP
.B \-man
List man pages (if any) in
.IR package .
.TP
.B \-lsman
List full path/filenames of man pages (if any) in
.IR package .
.TP
.B \-lsbin
List full path/filenames of executable files (if any) in
.IR package .
.PP

.SH ENVIRONMENT VARIABLES
.TP
.B COLUMNS
Sets the number of columns \fBdlocate\fP should use when displaying formatted
text.  Currently only used by \-l. Values lower than 80 are ignored.

.SH "SEE ALSO"
\fBlocate\fP(1),
\fBdpkg\fP(1),
\fBupdate\-dlocatedb\fP(8),
\fBegrep\fP(1)
and
\fBgrep\-dctrl\fP(1).



.SH AUTHOR
dlocate was written by Jim Pick <jim@pick.com> and Craig Sanders
<cas@taz.net.au>. dlocate is Free Software licensed under the GNU
General Public License.
